/*
const middle_categories = {
    "nouns": [
        "ability", "action", "adventure", "article", "artist", "atmosphere", "attention",
        "audience", "background", "balance", "behavior", "birth", "brain", "building",
        "camera", "celebration", "century", "challenge", "character", "chemistry", "choice",
        "circle", "climate", "clothing", "communication", "community", "company", "competition",
        "condition", "connection", "consequence", "construction", "content", "context", "control",
        "culture", "damage", "dance", "danger", "data", "decision", "design", "development",
        "difference", "direction", "discovery", "discussion", "disease", "distance", "distribution",
        "economy", "education", "effect", "effort", "energy", "environment", "event", "example",
        "experience", "experiment", "expression", "fact", "failure", "field", "figure", "food",
        "force", "form", "function", "future", "game", "garden", "goal", "government", "group",
        "growth", "health", "history", "idea", "image", "importance", "industry", "information",
        "injury", "insect", "interest", "invention", "issue", "job", "knowledge", "language",
        "law", "level", "limit", "location", "machine", "material", "matter", "meaning", "measure",
        "medicine", "method", "mind", "moment", "movement", "music", "nature", "need", "network",
        "number", "object", "observation", "opportunity", "order", "organization", "pain", "part",
        "pattern", "people", "performance", "period", "person", "picture", "plant", "point",
        "population", "power", "pressure", "problem", "process", "product", "production", "program",
        "property", "purpose", "quality", "question", "reaction", "reason", "record", "relation",
        "relationship", "result", "risk", "role", "rule", "safety", "science", "season", "sense",
        "service", "shape", "situation", "skill", "society", "solution", "sound", "space", "sport",
        "standard", "state", "story", "structure", "student", "study", "style", "subject", "success",
        "system", "table", "task", "team", "technology", "temperature", "term", "theory", "thing",
        "thought", "time", "tool", "tradition", "training", "transport", "tree", "trouble", "type",
        "unit", "value", "variety", "video", "view", "village", "voice", "war", "water", "way",
        "weather", "weight", "word", "work", "world", "writer", "year"
    ],
    "verbs": [
        "accept", "achieve", "act", "add", "admire", "admit", "advise", "affect", "agree", "allow",
        "announce", "answer", "appear", "apply", "argue", "arrive", "ask", "avoid", "become", "begin",
        "believe", "belong", "break", "bring", "build", "buy", "call", "carry", "catch", "cause",
        "change", "choose", "close", "collect", "come", "compare", "consider", "continue", "control", "create",
        "cut", "decide", "describe", "design", "destroy", "develop", "die", "discover", "discuss", "divide",
        "do", "draw", "dream", "drive", "drop", "eat", "encourage", "enjoy", "enter", "examine",
        "exist", "expect", "explain", "express", "fall", "feel", "fight", "find", "finish", "follow",
        "forget", "form", "get", "give", "go", "grow", "happen", "have", "hear", "help",
        "hide", "hold", "hope", "hurt", "imagine", "improve", "include", "increase", "indicate", "influence",
        "inform", "insist", "introduce", "invent", "invite", "join", "jump", "keep", "kill", "know",
        "laugh", "learn", "leave", "let", "lie", "like", "listen", "live", "look", "lose",
        "love", "make", "manage", "mean", "meet", "mention", "move", "need", "notice", "occur",
        "offer", "open", "order", "organize", "pass", "pay", "perform", "pick", "play", "prepare",
        "prevent", "produce", "promise", "protect", "prove", "provide", "pull", "push", "put", "raise",
        "reach", "read", "realize", "receive", "recognize", "record", "reduce", "refer", "reflect", "refuse",
        "regret", "relate", "relax", "remain", "remember", "remove", "repeat", "replace", "reply", "report",
        "represent", "require", "rest", "result", "return", "reveal", "run", "save", "say", "see",
        "seem", "sell", "send", "serve", "set", "show", "shut", "sing", "sit", "sleep",
        "smile", "solve", "speak", "spend", "stand", "start", "stay", "stop", "study", "succeed",
        "suggest", "support", "surprise", "take", "talk", "teach", "tell", "think", "throw", "touch",
        "train", "travel", "try", "turn", "understand", "use", "visit", "wait", "walk", "want",
        "warn", "watch", "win", "wish", "wonder", "work", "worry", "write"
    ],
    "adjectives": [
        "able", "active", "actual", "afraid", "amazing", "angry", "anxious", "aware", "bad", "beautiful",
        "best", "better", "big", "bitter", "black", "blue", "boring", "brave", "bright", "broad",
        "brown", "busy", "calm", "careful", "certain", "cheap", "clean", "clear", "clever", "close",
        "cold", "comfortable", "common", "complete", "complex", "confident", "conscious", "cool", "crazy", "creative",
        "critical", "curious", "dangerous", "dark", "dead", "deep", "different", "difficult", "direct", "dirty",
        "dry", "easy", "economic", "effective", "efficient", "electronic", "empty", "equal", "exact", "excellent",
        "exciting", "expensive", "fair", "famous", "fast", "fat", "fearful", "final", "financial", "fine",
        "flat", "foreign", "formal", "free", "fresh", "friendly", "full", "fun", "funny", "future",
        "general", "gentle", "glad", "golden", "good", "great", "green", "happy", "hard", "healthy",
        "heavy", "helpful", "high", "historical", "honest", "hot", "huge", "human", "hungry", "ideal",
        "important", "impossible", "independent", "individual", "industrial", "informal", "inner", "intelligent", "interesting", "international",
        "involved", "joint", "junior", "just", "key", "kind", "large", "late", "laughing", "legal",
        "light", "like", "likely", "little", "local", "logical", "lonely", "long", "loud", "low",
        "main", "major", "married", "material", "medical", "mental", "modern", "moral", "moving", "musical",
        "natural", "necessary", "negative", "new", "nice", "normal", "northern", "obvious", "old", "only",
        "open", "ordinary", "other", "outdoor", "outside", "over", "own", "particular", "patient", "perfect",
        "personal", "physical", "pink", "plain", "pleasant", "political", "poor", "popular", "positive", "possible",
        "powerful", "practical", "present", "pretty", "previous", "private", "probable", "professional", "proper", "proud",
        "public", "quick", "quiet", "rainy", "rapid", "rare", "ready", "real", "red", "regular",
        "related", "religious", "responsible", "rich", "right", "round", "sad", "safe", "same", "scientific",
        "secret", "senior", "serious", "sharp", "short", "shy", "sick", "silent", "simple", "single",
        "slow", "small", "smart", "smooth", "social", "soft", "solar", "solid", "special", "specific",
        "spiritual", "strange", "strong", "stupid", "successful", "sudden", "suitable", "sunny", "sure", "surprising",
        "sweet", "tall", "technical", "terrible", "thin", "thirsty", "tired", "total", "true", "typical",
        "ugly", "unable", "unhappy", "unique", "united", "unknown", "unusual", "useful", "usual", "valuable",
        "various", "warm", "weak", "wet", "white", "whole", "wide", "wild", "willing", "wise",
        "wonderful", "worried", "wrong", "yellow", "young"
    ],

        "adverbs": [
            "actually", "almost", "already", "anywhere", "anyway", "anyhow", "basically", "currently",
            "daily", "deeply", "directly", "eventually", "everywhere", "exactly", "fairly", "finally",
            "forever", "forward", "generally", "highly", "immediately", "instead", "last", "later",
            "least", "loudly", "maybe", "narly", "next", "nowhere", "otherwise", "perhaps", "probably",
            "quickly", "quietly", "rather", "recently", "seriously", "simply", "somehow", "sometimes",
            "soon", "straight", "suddenly", "therefore", "totally", "twice", "usually"
        ],
        "prepositions": [
            "across", "against", "along", "among", "around", "before", "behind", "below", "beside",
            "between", "beyond", "concerning", "despite", "during", "except", "inside", "into", "near",
            "onto", "outside", "over", "past", "regarding", "through", "throughout", "toward", "under",
            "upon", "within", "without"
        ],
        "conjunctions": [
            "although", "because", "if", "since", "though", "unless", "until", "when", "where", "while",
            "after", "even", "once", "whether", "while"
        ],
        "pronouns": [
            "myself", "yourself", "himself", "herself", "itself", "ourselves", "yourselves", "themselves",
            "this", "that", "these", "those", "who", "whom", "whose", "which", "what", "whatever", "whoever",
            "whichever", "somebody", "someone", "something", "anybody", "anyone", "anything", "nobody",
            "no one", "nothing", "everybody", "everyone", "everything", "few", "many", "several", "some",
            "any", "none", "all", "both", "either", "neither", "each", "every", "other", "another", "such",
            "same", "so", "as"
        ],
        "numbers": [
            "hundred", "thousand", "million", "billion"
        ]


}; */

const middleMap = {
    // Nouns
    "ability": "能力",
    "action": "行动",
    "adventure": "冒险",
    "article": "文章",
    "artist": "艺术家",
    "atmosphere": "气氛",
    "attention": "注意力",
    "audience": "观众",
    "background": "背景",
    "balance": "平衡",
    "behavior": "行为",
    "birth": "出生",
    "brain": "大脑",
    "building": "建筑物",
    "camera": "相机",
    "celebration": "庆祝",
    "century": "世纪",
    "challenge": "挑战",
    "character": "性格",
    "chemistry": "化学",
    "choice": "选择",
    "circle": "圆圈",
    "climate": "气候",
    "clothing": "服装",
    "communication": "沟通",
    "community": "社区",
    "company": "公司",
    "competition": "竞争",
    "condition": "条件",
    "connection": "连接",
    "consequence": "后果",
    "construction": "建设",
    "content": "内容",
    "context": "上下文",
    "control": "控制",
    "culture": "文化",
    "damage": "损害",
    "dance": "舞蹈",
    "danger": "危险",
    "data": "数据",
    "decision": "决定",
    "design": "设计",
    "development": "发展",
    "difference": "差异",
    "direction": "方向",
    "discovery": "发现",
    "discussion": "讨论",
    "disease": "疾病",
    "distance": "距离",
    "distribution": "分布",
    "economy": "经济",
    "education": "教育",
    "effect": "效果",
    "effort": "努力",
    "energy": "能量",
    "environment": "环境",
    "event": "事件",
    "example": "例子",
    "experience": "经验",
    "experiment": "实验",
    "expression": "表达",
    "fact": "事实",
    "failure": "失败",
    "field": "领域",
    "figure": "数字",
    "food": "食物",
    "force": "力量",
    "form": "形式",
    "function": "功能",
    "future": "未来",
    "game": "游戏",
    "garden": "花园",
    "goal": "目标",
    "government": "政府",
    "group": "群体",
    "growth": "增长",
    "health": "健康",
    "history": "历史",
    "idea": "想法",
    "image": "图像",
    "importance": "重要性",
    "industry": "工业",
    "information": "信息",
    "injury": "伤害",
    "insect": "昆虫",
    "interest": "兴趣",
    "invention": "发明",
    "issue": "问题",
    "job": "工作",
    "knowledge": "知识",
    "language": "语言",
    "law": "法律",
    "level": "水平",
    "limit": "限制",
    "location": "位置",
    "machine": "机器",
    "material": "材料",
    "matter": "物质",
    "meaning": "意义",
    "measure": "测量",
    "medicine": "医学",
    "method": "方法",
    "mind": "思想",
    "moment": "时刻",
    "movement": "运动",
    "music": "音乐",
    "nature": "自然",
    "need": "需求",
    "network": "网络",
    "number": "数字",
    "object": "物体",
    "observation": "观察",
    "opportunity": "机会",
    "order": "订单",
    "organization": "组织",
    "pain": "疼痛",
    "part": "部分",
    "pattern": "模式",
    "people": "人们",
    "performance": "表现",
    "period": "时期",
    "person": "人",
    "picture": "图片",
    "plant": "植物",
    "point": "点",
    "population": "人口",
    "power": "力量",
    "pressure": "压力",
    "problem": "问题",
    "process": "过程",
    "product": "产品",
    "production": "生产",
    "program": "程序",
    "property": "财产",
    "purpose": "目的",
    "quality": "质量",
    "question": "问题",
    "reaction": "反应",
    "reason": "原因",
    "record": "记录",
    "relation": "关系",
    "relationship": "关系",
    "result": "结果",
    "risk": "风险",
    "role": "角色",
    "rule": "规则",
    "safety": "安全",
    "science": "科学",
    "season": "季节",
    "sense": "感觉",
    "service": "服务",
    "shape": "形状",
    "situation": "情况",
    "skill": "技能",
    "society": "社会",
    "solution": "解决方案",
    "sound": "声音",
    "space": "空间",
    "sport": "运动",
    "standard": "标准",
    "state": "状态",
    "story": "故事",
    "structure": "结构",
    "student": "学生",
    "study": "学习",
    "style": "风格",
    "subject": "主题",
    "success": "成功",
    "system": "系统",
    "table": "桌子",
    "task": "任务",
    "team": "团队",
    "technology": "技术",
    "temperature": "温度",
    "term": "术语",
    "theory": "理论",
    "thing": "事物",
    "thought": "思想",
    "time": "时间",
    "tool": "工具",
    "tradition": "传统",
    "training": "培训",
    "transport": "运输",
    "tree": "树",
    "trouble": "麻烦",
    "type": "类型",
    "unit": "单元",
    "value": "价值",
    "variety": "多样性",
    "video": "视频",
    "view": "观点",
    "village": "村庄",
    "voice": "声音",
    "war": "战争",
    "water": "水",
    "way": "方式",
    "weather": "天气",
    "weight": "重量",
    "word": "单词",
    "work": "工作",
    "world": "世界",
    "writer": "作家",
    "year": "年",

    // Verbs
    "accept": "接受",
    "achieve": "实现",
    "act": "行动",
    "add": "添加",
    "admire": "欣赏",
    "admit": "承认",
    "advise": "建议",
    "affect": "影响",
    "agree": "同意",
    "allow": "允许",
    "announce": "宣布",
    "answer": "回答",
    "appear": "出现",
    "apply": "申请",
    "argue": "争论",
    "arrive": "到达",
    "ask": "问",
    "avoid": "避免",
    "become": "成为",
    "begin": "开始",
    "believe": "相信",
    "belong": "属于",
    "break": "打破",
    "bring": "带来",
    "build": "建造",
    "buy": "买",
    "call": "叫",
    "carry": "携带",
    "catch": "抓住",
    "cause": "引起",
    "change": "改变",
    "choose": "选择",
    "close": "关闭",
    "collect": "收集",
    "come": "来",
    "compare": "比较",
    "consider": "考虑",
    "continue": "继续",
    "control": "控制",
    "create": "创造",
    "cut": "切",
    "decide": "决定",
    "describe": "描述",
    "design": "设计",
    "destroy": "破坏",
    "develop": "发展",
    "die": "死",
    "discover": "发现",
    "discuss": "讨论",
    "divide": "分开",
    "dream": "做梦",
    "drive": "驾驶",
    "drop": "掉落",
    "eat": "吃",
    "encourage": "鼓励",
    "enjoy": "享受",
    "enter": "进入",
    "examine": "检查",
    "exist": "存在",
    "expect": "期待",
    "explain": "解释",
    "express": "表达",
    "fall": "落下",
    "feel": "感觉",
    "fight": "打架",
    "find": "找到",
    "finish": "完成",
    "follow": "跟随",
    "forget": "忘记",
    "form": "形成",
    "get": "得到",
    "give": "给",
    "grow": "成长",
    "happen": "发生",
    "have": "有",
    "hear": "听到",
    "help": "帮助",
    "hide": "隐藏",
    "hold": "握住",
    "hope": "希望",
    "hurt": "受伤",
    "imagine": "想象",
    "improve": "改进",
    "include": "包括",
    "increase": "增加",
    "indicate": "表明",
    "influence": "影响",
    "inform": "通知",
    "insist": "坚持",
    "introduce": "介绍",
    "invent": "发明",
    "invite": "邀请",
    "join": "加入",
    "jump": "跳",
    "keep": "保持",
    "kill": "杀死",
    "know": "知道",
    "laugh": "笑",
    "learn": "学习",
    "leave": "离开",
    "let": "让",
    "lie": "躺",
    "like": "喜欢",
    "live": "住",
    "lose": "丢失",
    "love": "爱",
    "make": "制作",
    "manage": "管理",
    "mean": "意思是",
    "meet": "遇见",
    "mention": "提到",
    "move": "移动",
    "need": "需要",
    "notice": "注意到",
    "occur": "发生",
    "offer": "提供",
    "order": "命令",
    "organize": "组织",
    "pass": "通过",
    "pay": "支付",
    "perform": "表演",
    "pick": "挑选",
    "prepare": "准备",
    "prevent": "防止",
    "produce": "生产",
    "promise": "承诺",
    "protect": "保护",
    "prove": "证明",
    "provide": "提供",
    "pull": "拉",
    "push": "推",
    "put": "放",
    "raise": "提高",
    "reach": "到达",
    "read": "读",
    "realize": "意识到",
    "receive": "收到",
    "recognize": "认出",
    "record": "记录",
    "reduce": "减少",
    "refer": "提到",
    "reflect": "反映",
    "refuse": "拒绝",
    "regret": "后悔",
    "relate": "相关",
    "relax": "放松",
    "remain": "保持",
    "remember": "记住",
    "remove": "移除",
    "repeat": "重复",
    "replace": "替换",
    "reply": "回复",
    "report": "报告",
    "represent": "代表",
    "require": "需要",
    "rest": "休息",
    "result": "结果",
    "return": "返回",
    "reveal": "揭示",
    "save": "保存",
    "seem": "似乎",
    "sell": "卖",
    "send": "发送",
    "serve": "服务",
    "set": "设置",
    "show": "展示",
    "shut": "关闭",
    "sing": "唱",
    "solve": "解决",
    "speak": "说",
    "spend": "花费",
    "stand": "站",
    "start": "开始",
    "stay": "停留",
    "succeed": "成功",
    "suggest": "建议",
    "support": "支持",
    "surprise": "惊讶",
    "take": "拿",
    "talk": "谈论",
    "teach": "教",
    "tell": "告诉",
    "throw": "扔",
    "touch": "触摸",
    "train": "训练",
    "travel": "旅行",
    "try": "尝试",
    "turn": "转动",
    "understand": "理解",
    "use": "使用",
    "visit": "参观",
    "wait": "等待",
    "want": "想要",
    "warn": "警告",
    "watch": "看",
    "win": "赢",
    "wish": "希望",
    "wonder": "想知道",
    "work": "工作",
    "worry": "担心",


    // Adjectives
    "able": "能干的",
    "active": "积极的",
    "actual": "实际的",
    "afraid": "害怕的",
    "amazing": "令人惊叹的",
    "anxious": "焦虑的",
    "aware": "意识到的",
    "bad": "坏的",
    "beautiful": "美丽的",
    "best": "最好的",
    "better": "更好的",
    "bitter": "苦的",
    "black": "黑色的",
    "blue": "蓝色的",
    "boring": "无聊的",
    "brave": "勇敢的",
    "bright": "明亮的",
    "broad": "宽阔的",
    "brown": "棕色的",
    "busy": "忙碌的",
    "calm": "平静的",
    "careful": "小心的",
    "certain": "确定的",
    "cheap": "便宜的",
    "clean": "干净的",
    "clear": "清晰的",
    "clever": "聪明的",
    "close": "近的",
    "comfortable": "舒适的",
    "common": "常见的",
    "complete": "完整的",
    "complex": "复杂的",
    "confident": "自信的",
    "conscious": "有意识的",
    "cool": "酷的",
    "crazy": "疯狂的",
    "creative": "有创造力的",
    "critical": "批判的",
    "curious": "好奇的",
    "dangerous": "危险的",
    "dark": "黑暗的",
    "dead": "死的",
    "deep": "深的",
    "different": "不同的",
    "difficult": "困难的",
    "direct": "直接的",
    "dirty": "脏的",
    "dry": "干的",
    "easy": "容易的",
    "economic": "经济的",
    "effective": "有效的",
    "efficient": "高效的",
    "electronic": "电子的",
    "empty": "空的",
    "equal": "平等的",
    "exact": "精确的",
    "excellent": "优秀的",
    "exciting": "令人兴奋的",
    "expensive": "昂贵的",
    "fair": "公平的",
    "famous": "著名的",
    "fast": "快的",
    "fat": "胖的",
    "fearful": "害怕的",
    "final": "最终的",
    "financial": "财务的",
    "fine": "好的",
    "flat": "平的",
    "foreign": "外国的",
    "formal": "正式的",
    "free": "自由的",
    "fresh": "新鲜的",
    "friendly": "友好的",
    "full": "满的",
    "fun": "有趣的",
    "funny": "滑稽的",
    "future": "未来的",
    "general": "一般的",
    "gentle": "温柔的",
    "glad": "高兴的",
    "golden": "金色的",
    "great": "伟大的",
    "hard": "硬的",
    "healthy": "健康的",
    "heavy": "重的",
    "helpful": "有帮助的",
    "high": "高的",
    "historical": "历史的",
    "honest": "诚实的",
    "huge": "巨大的",
    "human": "人类的",
    "hungry": "饿的",
    "ideal": "理想的",
    "important": "重要的",
    "impossible": "不可能的",
    "independent": "独立的",
    "individual": "个人的",
    "industrial": "工业的",
    "informal": "非正式的",
    "inner": "内部的",
    "intelligent": "聪明的",
    "interesting": "有趣的",
    "international": "国际的",
    "involved": "参与的",
    "joint": "联合的",
    "junior": "初级的",
    "just": "公正的",
    "key": "关键的",
    "kind": "善良的",
    "large": "大的",
    "late": "迟的",
    "laughing": "笑的",
    "legal": "合法的",
    "light": "轻的",
    "like": "像",
    "likely": "可能的",
    "little": "小的",
    "local": "当地的",
    "logical": "逻辑的",
    "lonely": "孤独的",
    "loud": "大声的",
    "low": "低的",
    "main": "主要的",
    "major": "主要的",
    "married": "已婚的",
    "material": "材料的",
    "medical": "医学的",
    "mental": "精神的",
    "modern": "现代的",
    "moral": "道德的",
    "moving": "感动的",
    "musical": "音乐的",
    "natural": "自然的",
    "necessary": "必要的",
    "negative": "消极的",
    "new": "新的",
    "nice": "好的",
    "normal": "正常的",
    "northern": "北方的",
    "obvious": "明显的",
    "only": "唯一的",
    "open": "开放的",
    "ordinary": "普通的",
    "other": "其他的",
    "outdoor": "户外的",
    "outside": "外面的",
    "over": "结束的",
    "own": "自己的",
    "particular": "特别的",
    "patient": "耐心的",
    "perfect": "完美的",
    "personal": "个人的",
    "physical": "身体的",
    "pink": "粉色的",
    "plain": "简单的",
    "pleasant": "愉快的",
    "political": "政治的",
    "poor": "贫穷的",
    "popular": "流行的",
    "positive": "积极的",
    "possible": "可能的",
    "powerful": "强大的",
    "practical": "实际的",
    "present": "现在的",
    "pretty": "漂亮的",
    "previous": "以前的",
    "private": "私人的",
    "probable": "可能的",
    "professional": "专业的",
    "proper": "合适的",
    "proud": "骄傲的",
    "public": "公共的",
    "quick": "快的",
    "quiet": "安静的",
    "rainy": "下雨的",
    "rapid": "迅速的",
    "rare": "稀有的",
    "ready": "准备好的",
    "real": "真实的",
    "regular": "定期的",
    "related": "相关的",
    "religious": "宗教的",
    "responsible": "负责的",
    "rich": "富有的",
    "right": "正确的",
    "round": "圆的",
    "sad": "悲伤的",
    "safe": "安全的",
    "scientific": "科学的",
    "secret": "秘密的",
    "senior": "高级的",
    "serious": "严肃的",
    "sharp": "锋利的",
    "short": "短的",
    "shy": "害羞的",
    "sick": "生病的",
    "silent": "沉默的",
    "simple": "简单的",
    "single": "单一的",
    "slow": "慢的",
    "small": "小的",
    "smart": "聪明的",
    "smooth": "光滑的",
    "social": "社会的",
    "soft": "软的",
    "solar": "太阳的",
    "solid": "固体的",
    "special": "特别的",
    "specific": "特定的",
    "spiritual": "精神的",
    "strange": "奇怪的",
    "strong": "强壮的",
    "stupid": "愚蠢的",
    "successful": "成功的",
    "sudden": "突然的",
    "suitable": "合适的",
    "sunny": "晴朗的",
    "sure": "确定的",
    "surprising": "令人惊讶的",
    "sweet": "甜的",
    "tall": "高的",
    "technical": "技术的",
    "terrible": "可怕的",
    "thin": "薄的",
    "thirsty": "口渴的",
    "tired": "累的",
    "total": "全部的",
    "true": "真实的",
    "typical": "典型的",
    "ugly": "丑陋的",
    "unable": "不能的",
    "unhappy": "不开心的",
    "unique": "独特的",
    "united": "联合的",
    "unknown": "未知的",
    "unusual": "不寻常的",
    "useful": "有用的",
    "usual": "通常的",
    "valuable": "有价值的",
    "various": "各种各样的",
    "weak": "弱的",
    "wet": "湿的",
    "white": "白色的",
    "whole": "整个的",
    "wide": "宽的",
    "wild": "野生的",
    "willing": "愿意的",
    "wise": "明智的",
    "wonderful": "精彩的",
    "worried": "担心的",
  

        // Adverbs
        "actually": "实际上",
        "almost": "几乎",
        "already": "已经",
        "anywhere": "任何地方",
        "anyway": "无论如何",
        "anyhow": "不管怎样",
        "basically": "基本上",
        "currently": "目前",
        "daily": "每天",
        "deeply": "深深地",
        "directly": "直接地",
        "eventually": "最终",
        "everywhere": "到处",
        "exactly": "确切地",
        "fairly": "相当地",
        "finally": "最后",
        "forever": "永远",
        "forward": "向前",
        "generally": "通常",
        "highly": "高度地",
        "immediately": "立即",
        "instead": "反而",
        "last": "最后",
        "later": "后来",
        "least": "最少",
        "loudly": "大声地",
        "maybe": "也许",
        "nearly": "几乎",
        "next": "下一个",
        "nowhere": "无处",
        "otherwise": "否则",
        "perhaps": "也许",
        "probably": "可能",
        "quickly": "迅速地",
        "quietly": "安静地",
        "rather": "相当",
        "recently": "最近",
        "seriously": "认真地",
        "simply": "简单地",
        "somehow": "以某种方式",
        "sometimes": "有时",
        "soon": "很快",
        "straight": "直接地",
        "suddenly": "突然地",
        "therefore": "因此",
        "totally": "完全地",
        "twice": "两次",
        "usually": "通常",
    
        // Prepositions
        "across": "穿过",
        "against": "反对",
        "along": "沿着",
        "among": "在...之中",
        "around": "在...周围",
        "before": "在...之前",
        "behind": "在...后面",
        "below": "在...下面",
        "beside": "在...旁边",
        "between": "在...之间",
        "beyond": "超出",
        "concerning": "关于",
        "despite": "尽管",
        "during": "在...期间",
        "except": "除了",
        "inside": "在...内部",
        "into": "进入",
        "near": "靠近",
        "onto": "到...上面",
        "outside": "在...外面",
        "over": "在...上方",
        "past": "经过",
        "regarding": "关于",
        "through": "通过",
        "throughout": "遍及",
        "toward": "朝向",
        "under": "在...下面",
        "upon": "在...上面",
        "within": "在...之内",
        "without": "没有",
    
        // Conjunctions
        "although": "虽然",
        "because": "因为",
        "if": "如果",
        "since": "自从",
        "though": "虽然",
        "unless": "除非",
        "until": "直到",
        "when": "当...时",
        "where": "在...地方",
        "while": "当...时",
        "after": "在...之后",
        "even": "即使",
        "once": "一旦",
        "whether": "是否",
        "while": "而",
    
        // Pronouns
        "myself": "我自己",
        "yourself": "你自己",
        "himself": "他自己",
        "herself": "她自己",
        "itself": "它自己",
        "ourselves": "我们自己",
        "yourselves": "你们自己",
        "themselves": "他们自己",
        "this": "这个",
        "that": "那个",
        "these": "这些",
        "those": "那些",
        "who": "谁",
        "whom": "谁",
        "whose": "谁的",
        "which": "哪个",
        "what": "什么",
        "whatever": "无论什么",
        "whoever": "无论谁",
        "whichever": "无论哪个",
        "somebody": "某人",
        "someone": "某人",
        "something": "某事",
        "anybody": "任何人",
        "anyone": "任何人",
        "anything": "任何事",
        "nobody": "没有人",
        "no one": "没有人",
        "nothing": "没有事",
        "everybody": "每个人",
        "everyone": "每个人",
        "everything": "每件事",
        "few": "很少",
        "many": "许多",
        "several": "几个",
        "some": "一些",
        "any": "任何",
        "none": "没有",
        "all": "所有",
        "both": "两者都",
        "either": "任何一个",
        "neither": "两者都不",
        "each": "每个",
        "every": "每个",
        "other": "其他",
        "another": "另一个",
        "such": "这样的",
        "same": "相同的",
        "so": "如此",
        "as": "作为",
    
        // Numbers
        "hundred": "百",
        "thousand": "千",
        "million": "百万",
        "billion": "十亿"

};